server:
  port: 8081

spring:
  application:
    name: auth-service

# Sample DB Config (used by auth-service)
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: password
