spring:
  datasource:
    url: jdbc:mysql://localhost:3306/edumantra
    username: root
    password: Rania@01
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
